# Generated by Django 4.2.7 on 2023-11-08 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Info",
        ),
    ]
